#!/bin/bash

# Manual PoC Test Script
# Creates a test zone with records to verify Bind integration

echo "🧪 NDash PoC - Manual Integration Test"
echo "======================================"
echo ""

ZONE_NAME="poc-test.local"
ZONE_FILE="/etc/bind/zones/db.$ZONE_NAME"

echo "📋 Test Plan:"
echo "1. Create zone: $ZONE_NAME"
echo "2. Add multiple DNS records"
echo "3. Verify zone file"
echo "4. Test DNS resolution"
echo "5. Cleanup"
echo ""

read -p "Press Enter to start the test..."

echo ""
echo "Step 1: Creating test zone..."
echo "------------------------------"

# Create zone file
sudo bash -c "cat > $ZONE_FILE" << EOF
; Zone file for $ZONE_NAME
; Generated by NDash PoC Test
\$TTL 3600
@       IN      SOA     ns1.$ZONE_NAME. admin.$ZONE_NAME. (
                        2025111401 ; Serial
                        86400      ; Refresh
                        7200       ; Retry
                        3600000    ; Expire
                        86400 )    ; Minimum TTL

; Name servers
@       IN      NS      ns1.$ZONE_NAME.

; A records
@       IN      A       192.168.100.1
ns1     IN      A       192.168.100.1
www     IN      A       192.168.100.10
mail    IN      A       192.168.100.20

; CNAME records
ftp     IN      CNAME   www.$ZONE_NAME.
webmail IN      CNAME   www.$ZONE_NAME.

; MX records
@       IN      MX      10 mail.$ZONE_NAME.

; TXT records
@       IN      TXT     "v=spf1 mx -all"
_dmarc  IN      TXT     "v=DMARC1; p=quarantine; rua=mailto:postmaster@$ZONE_NAME"
EOF

if [ -f "$ZONE_FILE" ]; then
    echo "✅ Zone file created: $ZONE_FILE"
else
    echo "❌ Failed to create zone file"
    exit 1
fi

echo ""
echo "Step 2: Validating zone syntax..."
echo "---------------------------------"
sudo named-checkzone "$ZONE_NAME" "$ZONE_FILE"

if [ $? -eq 0 ]; then
    echo "✅ Zone syntax is valid"
else
    echo "❌ Zone syntax validation failed"
    exit 1
fi

echo ""
echo "Step 3: Adding zone to named.conf.local..."
echo "------------------------------------------"

# Check if zone already exists in config
if sudo grep -q "zone \"$ZONE_NAME\"" /etc/bind/named.conf.local; then
    echo "⚠️  Zone already in config, removing old entry..."
    sudo sed -i "/zone \"$ZONE_NAME\"/,/};/d" /etc/bind/named.conf.local
fi

# Add zone to config
sudo bash -c "cat >> /etc/bind/named.conf.local" << EOF

zone "$ZONE_NAME" {
    type master;
    file "$ZONE_FILE";
    allow-update { none; };
};
EOF

echo "✅ Zone added to named.conf.local"

echo ""
echo "Step 4: Validating Bind configuration..."
echo "----------------------------------------"
sudo named-checkconf

if [ $? -eq 0 ]; then
    echo "✅ Bind configuration is valid"
else
    echo "❌ Bind configuration validation failed"
    exit 1
fi

echo ""
echo "Step 5: Reloading Bind service..."
echo "---------------------------------"
sudo rndc reload

if [ $? -eq 0 ]; then
    echo "✅ Bind reloaded successfully"
else
    echo "❌ Bind reload failed"
    exit 1
fi

echo ""
echo "Step 6: Verifying zone is loaded..."
echo "-----------------------------------"
sudo rndc status | grep -i zone

echo ""
echo "Step 7: Testing DNS resolution..."
echo "---------------------------------"
echo ""

echo "Testing A record (@):"
dig @localhost $ZONE_NAME A +short

echo ""
echo "Testing A record (www):"
dig @localhost www.$ZONE_NAME A +short

echo ""
echo "Testing CNAME record (ftp):"
dig @localhost ftp.$ZONE_NAME CNAME +short

echo ""
echo "Testing MX record:"
dig @localhost $ZONE_NAME MX +short

echo ""
echo "Testing TXT record:"
dig @localhost $ZONE_NAME TXT +short

echo ""
echo "Step 8: Displaying zone file content..."
echo "---------------------------------------"
sudo cat $ZONE_FILE

echo ""
echo "======================================"
echo "✅ PoC Test Completed Successfully!"
echo "======================================"
echo ""
echo "📊 Summary:"
echo "  - Zone created: $ZONE_NAME"
echo "  - Zone file: $ZONE_FILE"
echo "  - Records: 10+ (A, CNAME, MX, TXT)"
echo "  - Bind reloaded: Yes"
echo "  - DNS resolution: Working"
echo ""
echo "🧹 Cleanup Instructions:"
echo "  To remove test zone:"
echo "  sudo rm -f $ZONE_FILE"
echo "  sudo sed -i '/zone \"$ZONE_NAME\"/,/};/d' /etc/bind/named.conf.local"
echo "  sudo rndc reload"
echo ""
echo "🌐 Next: Start NDash and test via web interface"
echo "  cd /opt/ndash && npm start"
echo "  Then visit: http://localhost:3000"
echo ""
